GCC=gcc
CXX=g++
PKG_CONFIG=pkg-config

CFLAGS=-Wall -Wno-deprecated-declarations -std=c++17 $(shell $(PKG_CONFIG) --cflags librsvg-2.0 cairo Qt5Core Qt5Widgets)
CXXFLAGS=$(CFLAGS)

LDFLAGS=-static
LIBS=$(shell $(PKG_CONFIG) --libs librsvg-2.0 cairo Qt5Core Qt5Widgets)

all: test
main: main.cpp
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $< $(LIBS) -o $@
test: main
	wine ./main
clean:
	$(RM) main
